name: MERN CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # -------------------
  # 1. Server (Node.js/Express) Tests
  # -------------------
  server-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ping: 1})'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install server dependencies
        working-directory: ./server
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run server tests
        working-directory: ./server
        run: |
          echo "Running tests with NODE_ENV=test"
          NODE_ENV=test npm test
        env:
          NODE_ENV: test
          MONGO_URI: mongodb://localhost:27017/issue_tracker_test
          PORT: 5000

  # -------------------
  # 2. Client (React) Tests
  # -------------------
  client-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install client dependencies
        working-directory: ./client
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run client tests and build
        working-directory: ./client
        run: |
          npm test
          npm run build
        env:
          CI: true


  # -------------------
  # 3. Docker Compose Validation
  # -------------------
  docker-compose-test:
    runs-on: ubuntu-latest
    needs: [server-test, client-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build with Docker Compose
        run: docker compose build

      - name: Test Docker Compose startup
        run: |
          docker compose up -d
          echo "Waiting for services to be ready..."
          
          # Wait for MongoDB to be ready
          timeout 30 bash -c 'until docker compose exec -T mongodb mongosh --eval "db.adminCommand({ping:1})" > /dev/null 2>&1; do echo "Waiting for MongoDB..." && sleep 2; done'
          
          # Wait for server to be ready
          timeout 30 bash -c 'until curl -s http://localhost:5000/health > /dev/null; do echo "Waiting for server..." && sleep 2; done'
          
          # Final health check
          curl --fail http://localhost:5000/health
          
          # Show running containers
          docker compose ps
          
          # Cleanup
          docker compose down
